import fs from 'node:fs'
import path from 'node:path'

const catalogPath = path.resolve('data/use-cases.json')
const readmePath = path.resolve('README.md')
const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'))

const categoryPresentation = {
  video: { emoji: '🎬', heading: 'AI Video Prompts & Use Cases' },
  'poster-and-flyer': { emoji: '🪧', heading: 'Poster & Flyer Prompts & Use Cases' },
  'image-editor': { emoji: '🪄', heading: 'AI Image Editing Prompts & Use Cases' },
  'e-commerce': { emoji: '🛍️', heading: 'E-commerce Creative Prompts & Use Cases' },
  document: { emoji: '📄', heading: 'Document & Webpage Prompts & Use Cases' },
  slides: { emoji: '📊', heading: 'Presentation Prompts & Use Cases' },
  'social-post': { emoji: '📱', heading: 'Social Media Prompts & Use Cases' },
}

const outputLabels = {
  image: 'Image',
  video: 'Video',
  document: 'Document',
  slides: 'Presentation',
  webpage: 'Webpage',
}

function appendTracking(urlValue, content) {
  const url = new URL(urlValue)
  url.searchParams.set('utm_source', 'github')
  url.searchParams.set('utm_medium', 'referral')
  url.searchParams.set('utm_campaign', 'awesome-ai-prompts-and-use-cases')
  url.searchParams.set('utm_content', content)
  return url.toString()
}

function markdownFence(value) {
  const runs = value.match(/`+/g) || []
  const longest = Math.max(3, ...runs.map((run) => run.length + 1))
  return '`'.repeat(longest)
}

function escapeAlt(value) {
  return value.replace(/[\[\]]/g, '').replace(/"/g, '&quot;')
}

function previewUrl(item) {
  return item.result.coverUrl || item.result.assets.find((asset) => asset.url)?.url || ''
}

const categoryTable = catalog.categories
  .map((category) => {
    const presentation = categoryPresentation[category.slug]
    const websiteCategoryUrl = appendTracking(
      `https://www.pagepop.ai/use-cases/categories/${category.slug}`,
      `category-${category.slug}`,
    )
    return `| ${presentation.emoji} [${category.label}](#${category.slug}) | ${category.caseCount} | [Browse on PagePop](${websiteCategoryUrl}) |`
  })
  .join('\n')

let markdown = `<!-- This file is generated by scripts/generate-readme.mjs. Do not edit it manually. -->

# ${catalog.title}

[![Use cases](https://img.shields.io/badge/real--world_use_cases-${catalog.cases.length}-8B3FEF)](https://www.pagepop.ai/use-cases?utm_source=github&utm_medium=referral&utm_campaign=awesome-ai-prompts-and-use-cases&utm_content=badge)
[![Prompts](https://img.shields.io/badge/full_prompts-${catalog.cases.length}-FFE063)](#browse-all-prompts-and-use-cases)
[![Models](https://img.shields.io/badge/models-5-58D6C7)](#models-used-by-pagepop)
[![PRs welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](CONTRIBUTING.md)

> **Real requests. Natural-language prompts. Finished creative work.**
>
> A curated PagePop collection showing the exact prompt that started each project and the result it produced—without requiring specialized prompt engineering.

<p align="center">
  <a href="https://www.pagepop.ai/use-cases?utm_source=github&utm_medium=referral&utm_campaign=awesome-ai-prompts-and-use-cases&utm_content=hero"><strong>Browse the visual gallery on PagePop →</strong></a>
</p>

## Models used by PagePop

PagePop combines leading creative models and automatically selects the right implementation for the requested result:

**Nano Banana Pro** · **GPT Image 2** · **Seedance 2.0** · **Seedance 2.5** · **Gemini 3 Pro**

<a id="browse-all-prompts-and-use-cases"></a>

## Browse all prompts and use cases

All ${catalog.cases.length} prompts are included in this README. Use the category links below or search this page with <kbd>Ctrl</kbd>/<kbd>⌘</kbd> + <kbd>F</kbd>.

| Category | Prompts | Visual gallery |
| --- | ---: | --- |
${categoryTable}

---

`

let globalIndex = 0

for (const category of catalog.categories) {
  const presentation = categoryPresentation[category.slug]
  const categoryCases = catalog.cases.filter((item) => item.category === category.slug)

  markdown += `<a id="${category.slug}"></a>\n\n## ${presentation.emoji} ${presentation.heading}\n\n`
  markdown += `[Browse the ${category.label} gallery on PagePop →](${appendTracking(
    `https://www.pagepop.ai/use-cases/categories/${category.slug}`,
    `category-heading-${category.slug}`,
  )})\n\n`

  for (const item of categoryCases) {
    globalIndex += 1
    const image = previewUrl(item)
    const detailUrl = appendTracking(item.websiteUrl, `case-${item.slug}`)
    const createUrl = appendTracking(item.websiteUrl, `create-${item.slug}`)
    const fence = markdownFence(item.originalPrompt)
    const assetCount = item.result.assets.length

    markdown += `### ${String(globalIndex).padStart(2, '0')}. ${item.title}\n\n`

    if (image) {
      markdown += `<p align="center">\n  <a href="${detailUrl}"><img src="${image}" alt="${escapeAlt(
        `${item.title} — generated ${outputLabels[item.result.kind] || item.result.kind} result`,
      )}" width="720"></a>\n</p>\n\n`
    }

    markdown += `**Output:** ${outputLabels[item.result.kind] || item.result.kind} · **Result assets:** ${assetCount}\n\n`
    markdown += `#### Original prompt\n\n${fence}text\n${item.originalPrompt}\n${fence}\n\n`
    markdown += `**[View the complete creative process →](${detailUrl})** · **[Create in PagePop →](${createUrl})**\n\n---\n\n`
  }
}

markdown += `## How PagePop turns a prompt into a result

1. Start with an ordinary description of what you want.
2. PagePop asks for missing details only when they matter.
3. PagePop selects and coordinates the appropriate models and tools.
4. Continue refining the result through natural conversation.

The interactive result, complete public conversation, HTML/DOCX rendering, and remix flow remain on the corresponding PagePop use-case page.

## Contributing

New prompts and use cases are welcome. Read [CONTRIBUTING.md](CONTRIBUTING.md) and submit a use case through the repository issue template. Every submission must include an original prompt, a result preview, source information, and confirmation that the contributor has the right to publish the material.

## Data

The public, machine-readable catalog is available at [data/use-cases.json](data/use-cases.json). It intentionally excludes private conversations, internal identifiers, tool traces, and unpublished material.

## Rights and licensing

The repository is being prepared for public launch. Until a public content license is selected, all prompts, previews, and PagePop materials remain © PagePop and their respective contributors. Do not reuse them outside the permissions provided by the linked source.

---

<p align="center">
  <strong>Describe what you want. PagePop handles how it gets made.</strong><br><br>
  <a href="https://www.pagepop.ai/use-cases?utm_source=github&utm_medium=referral&utm_campaign=awesome-ai-prompts-and-use-cases&utm_content=footer">Explore every use case on PagePop →</a>
</p>
`

fs.writeFileSync(readmePath, markdown)
console.log(`Generated ${readmePath} with ${globalIndex} complete prompts.`)
